"""
==========================================================
AgentX Startup Builder
Professional PDF Export Engine
File: backend/exports/pdf.py
==========================================================
"""

import os
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.lib.pagesizes import A4

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    PageBreak,
    Table,
    TableStyle
)

from reportlab.pdfbase import pdfmetrics

from reportlab.graphics.shapes import Drawing
from reportlab.graphics.charts.barcharts import VerticalBarChart


# ==========================================================
# COLORS
# ==========================================================

PRIMARY = colors.HexColor("#2563EB")
SECONDARY = colors.HexColor("#0F172A")
ACCENT = colors.HexColor("#14B8A6")
LIGHT = colors.HexColor("#F8FAFC")
GRAY = colors.HexColor("#64748B")
SUCCESS = colors.HexColor("#16A34A")


# ==========================================================
# STYLES
# ==========================================================

styles = getSampleStyleSheet()

title_style = styles["Heading1"]
title_style.alignment = TA_CENTER
title_style.textColor = PRIMARY
title_style.spaceAfter = 20

heading_style = styles["Heading2"]
heading_style.textColor = PRIMARY
heading_style.spaceAfter = 10

subheading_style = styles["Heading3"]
subheading_style.textColor = SECONDARY

normal_style = styles["BodyText"]
normal_style.leading = 18
normal_style.spaceAfter = 8

center_style = styles["BodyText"]
center_style.alignment = TA_CENTER
center_style.leading = 18

small_style = styles["BodyText"]
small_style.fontSize = 9
small_style.textColor = GRAY


# ==========================================================
# PAGE FOOTER
# ==========================================================

def add_page_number(canvas, doc):
    """
    Footer displayed on every page.
    """

    page = canvas.getPageNumber()

    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    canvas.setFillColor(colors.grey)

    canvas.drawString(
        inch,
        0.5 * inch,
        f"Generated by AgentX Startup Builder"
    )

    canvas.drawRightString(
        A4[0] - inch,
        0.5 * inch,
        f"Page {page}"
    )

    canvas.restoreState()


# ==========================================================
# SECTION TITLE
# ==========================================================

def section_title(text):

    return Paragraph(text, heading_style)


# ==========================================================
# PARAGRAPH
# ==========================================================

def paragraph(text):

    if text is None:
        text = ""

    return Paragraph(str(text), normal_style)


# ==========================================================
# SIMPLE TABLE
# ==========================================================

def create_table(data):

    table = Table(data)

    table.setStyle(TableStyle([

        ("BACKGROUND", (0,0), (-1,0), PRIMARY),

        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("GRID",(0,0),(-1,-1),0.5,colors.grey),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("BOTTOMPADDING",(0,0),(-1,0),10),

        ("BACKGROUND",(0,1),(-1,-1),LIGHT),

        ("VALIGN",(0,0),(-1,-1),"TOP"),

    ]))

    return table


# ==========================================================
# COVER PAGE
# ==========================================================

def add_cover(story, startup):

    story.append(Spacer(1, 1.2 * inch))

    story.append(
        Paragraph(
            "AgentX Startup Builder",
            title_style
        )
    )

    story.append(
        Paragraph(
            "AI Generated Startup Report",
            subheading_style
        )
    )

    story.append(Spacer(1,0.4*inch))

    startup_name = startup.get(
        "startup_name",
        "Untitled Startup"
    )

    story.append(
        Paragraph(
            startup_name,
            title_style
        )
    )

    story.append(Spacer(1,0.2*inch))

    created = datetime.now().strftime("%d %B %Y")

    story.append(
        Paragraph(
            f"Generated on {created}",
            center_style
        )
    )

    story.append(Spacer(1,2*inch))

    story.append(
        Paragraph(
            "Confidential Business Report",
            center_style
        )
    )

    story.append(PageBreak())


# ==========================================================
# SUMMARY TABLE
# ==========================================================

def add_summary(story, startup):

    story.append(section_title("Startup Summary"))

    data = [

        ["Field","Value"],

        ["Startup Name",
         startup.get("startup_name","-")],

        ["Industry",
         startup.get("industry","-")],

        ["Target Audience",
         startup.get("target_audience","-")],

        ["Estimated Budget",
         startup.get("budget","-")],

        ["Business Model",
         startup.get("business_model","-")],

    ]

    story.append(create_table(data))

    story.append(Spacer(1,20))


# ==========================================================
# BAR CHART
# ==========================================================

def add_chart(story):

    drawing = Drawing(400,220)

    chart = VerticalBarChart()

    chart.x = 40

    chart.y = 40

    chart.height = 140

    chart.width = 280

    chart.data = [

        (60,80,75,90)

    ]

    chart.categoryAxis.categoryNames = [

        "Market",

        "Finance",

        "Branding",

        "Growth"

    ]

    drawing.add(chart)

    story.append(drawing)

    story.append(Spacer(1,20))


# ==========================================================
# MAIN FUNCTION
# ==========================================================

def generate_startup_pdf(startup, output_path):

    """
    Generates a professional PDF report.

    Parameters

    startup : dict

    output_path : str
    """

    doc = SimpleDocTemplate(

        output_path,

        pagesize=A4,

        rightMargin=40,

        leftMargin=40,

        topMargin=40,

        bottomMargin=60

    )

    story = []

    # Cover

    add_cover(story, startup)

    # Summary

    add_summary(story, startup)

    # Placeholder chart

    add_chart(story)

    # Remaining sections will be added
    # in Part 2

    doc.build(

        story,

        onFirstPage=add_page_number,

        onLaterPages=add_page_number

    )

    return output_path
# ==========================================================
# EXECUTIVE SUMMARY
# ==========================================================

def add_executive_summary(story, startup):

    story.append(section_title("Executive Summary"))

    summary = startup.get(
        "executive_summary",
        "No executive summary available."
    )

    story.append(paragraph(summary))

    story.append(Spacer(1,20))


# ==========================================================
# BUSINESS PLAN
# ==========================================================

def add_business_plan(story, startup):

    story.append(section_title("Business Plan"))

    business = startup.get("business_plan", {})

    sections = [

        ("Problem", business.get("problem")),

        ("Solution", business.get("solution")),

        ("Unique Selling Proposition",
         business.get("usp")),

        ("Business Model",
         business.get("business_model")),

        ("Revenue Streams",
         business.get("revenue_streams")),

        ("Growth Strategy",
         business.get("growth_strategy")),

        ("SWOT Analysis",
         business.get("swot"))

    ]

    for title, value in sections:

        story.append(
            Paragraph(
                f"<b>{title}</b>",
                subheading_style
            )
        )

        story.append(
            paragraph(value)
        )

        story.append(
            Spacer(1,8)
        )

    story.append(Spacer(1,20))


# ==========================================================
# MARKET RESEARCH
# ==========================================================

def add_market_research(story, startup):

    story.append(
        section_title("Market Research")
    )

    market = startup.get(
        "market",
        {}
    )

    fields = [

        ("Industry",
         market.get("industry")),

        ("Target Audience",
         market.get("target_audience")),

        ("Market Size",
         market.get("market_size")),

        ("Market Trends",
         market.get("trends")),

        ("Customer Persona",
         market.get("customer_persona")),

        ("Opportunities",
         market.get("opportunities")),

        ("Challenges",
         market.get("challenges")),

        ("Risks",
         market.get("risks"))

    ]

    table_data = [

        ["Category","Details"]

    ]

    for key, value in fields:

        table_data.append([

            key,

            value if value else "-"

        ])

    story.append(
        create_table(table_data)
    )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# MARKET INSIGHTS
# ==========================================================

def add_market_insights(story, startup):

    story.append(

        section_title(

            "AI Market Insights"

        )

    )

    insights = startup.get(

        "market",

        {}

    ).get(

        "insights",

        []

    )

    if not insights:

        story.append(

            paragraph(

                "No market insights available."

            )

        )

    else:

        for item in insights:

            story.append(

                Paragraph(

                    f"• {item}",

                    normal_style

                )

            )

    story.append(

        Spacer(1,20)

    )


# ==========================================================
# CUSTOMER PERSONA
# ==========================================================

def add_customer_persona(story, startup):

    story.append(

        section_title(

            "Ideal Customer Persona"

        )

    )

    persona = startup.get(

        "market",

        {}

    ).get(

        "persona",

        {}

    )

    data = [

        ["Attribute","Value"],

        ["Age",

         persona.get("age","-")],

        ["Occupation",

         persona.get("occupation","-")],

        ["Income",

         persona.get("income","-")],

        ["Location",

         persona.get("location","-")],

        ["Goals",

         persona.get("goals","-")],

        ["Pain Points",

         persona.get("pain_points","-")]

    ]

    story.append(

        create_table(data)

    )

    story.append(

        Spacer(1,20)

    )
    # ==========================================================
# COMPETITOR ANALYSIS
# ==========================================================

def add_competitor_analysis(story, startup):

    story.append(section_title("Competitor Analysis"))

    competitors = startup.get("competitors", [])

    if not competitors:

        story.append(
            paragraph("No competitor analysis available.")
        )

        story.append(Spacer(1, 20))
        return

    table = [["Competitor", "Strength", "Weakness"]]

    for competitor in competitors:

        table.append([
            competitor.get("name", "-"),
            competitor.get("strength", "-"),
            competitor.get("weakness", "-")
        ])

    story.append(create_table(table))
    story.append(Spacer(1, 20))


# ==========================================================
# COMPETITIVE ADVANTAGE
# ==========================================================

def add_competitive_advantage(story, startup):

    story.append(section_title("Competitive Advantage"))

    advantages = startup.get(
        "competitive_advantages",
        []
    )

    if not advantages:

        story.append(
            paragraph("No competitive advantages available.")
        )

    else:

        for advantage in advantages:

            story.append(
                Paragraph(
                    f"• {advantage}",
                    normal_style
                )
            )

    story.append(Spacer(1,20))


# ==========================================================
# BRANDING
# ==========================================================

def add_branding(story, startup):

    story.append(section_title("Brand Identity"))

    branding = startup.get("branding", {})

    items = [

        ("Startup Name",
         branding.get("brand_name")),

        ("Tagline",
         branding.get("tagline")),

        ("Brand Story",
         branding.get("brand_story")),

        ("Mission",
         branding.get("mission")),

        ("Vision",
         branding.get("vision"))

    ]

    for title, value in items:

        story.append(
            Paragraph(
                f"<b>{title}</b>",
                subheading_style
            )
        )

        story.append(
            paragraph(value)
        )

        story.append(
            Spacer(1,8)
        )

    story.append(Spacer(1,20))


# ==========================================================
# BRAND COLORS
# ==========================================================

def add_brand_colors(story, startup):

    story.append(section_title("Brand Color Palette"))

    branding = startup.get("branding", {})

    colors_used = branding.get("colors", [])

    if not colors_used:

        story.append(
            paragraph("No color palette generated.")
        )

        story.append(Spacer(1,20))
        return

    table = [["Primary Colors"]]

    for color in colors_used:

        table.append([color])

    story.append(create_table(table))
    story.append(Spacer(1,20))


# ==========================================================
# TYPOGRAPHY
# ==========================================================

def add_typography(story, startup):

    story.append(section_title("Typography"))

    fonts = startup.get(
        "branding",
        {}
    ).get(
        "fonts",
        []
    )

    if not fonts:

        story.append(
            paragraph("No font recommendations.")
        )

    else:

        for font in fonts:

            story.append(
                Paragraph(
                    f"• {font}",
                    normal_style
                )
            )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# DOMAIN SUGGESTIONS
# ==========================================================

def add_domain_names(story, startup):

    story.append(
        section_title(
            "Domain Suggestions"
        )
    )

    domains = startup.get(
        "branding",
        {}
    ).get(
        "domains",
        []
    )

    if not domains:

        story.append(
            paragraph("No domain suggestions.")
        )

    else:

        for domain in domains:

            story.append(
                Paragraph(
                    f"• {domain}",
                    normal_style
                )
            )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# SOCIAL MEDIA HANDLES
# ==========================================================

def add_social_handles(story, startup):

    story.append(
        section_title(
            "Suggested Social Handles"
        )
    )

    handles = startup.get(
        "branding",
        {}
    ).get(
        "social_handles",
        []
    )

    if not handles:

        story.append(
            paragraph("No social handles generated.")
        )

    else:

        for handle in handles:

            story.append(
                Paragraph(
                    f"• {handle}",
                    normal_style
                )
            )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# BRAND SCORE
# ==========================================================

def add_brand_score(story, startup):

    story.append(
        section_title(
            "Brand Evaluation"
        )
    )

    score = startup.get(
        "branding",
        {}
    ).get(
        "brand_score",
        "Not Available"
    )

    table = [

        ["Brand Metric", "Score"],

        ["Overall Brand Score", score]

    ]

    story.append(
        create_table(table)
    )

    story.append(
        Spacer(1,20)
    )
    # ==========================================================
# FINANCIAL REPORT
# ==========================================================

def add_financial_report(story, startup):

    story.append(section_title("Financial Report"))

    finance = startup.get("financial", {})

    table = [

        ["Financial Metric", "Value"],

        ["Initial Investment", finance.get("startup_cost", "-")],

        ["Monthly Operating Cost", finance.get("monthly_expense", "-")],

        ["Expected Monthly Revenue", finance.get("monthly_revenue", "-")],

        ["Expected Monthly Profit", finance.get("monthly_profit", "-")],

        ["Break-even Period", finance.get("break_even", "-")],

        ["Return on Investment (ROI)", finance.get("roi", "-")]

    ]

    story.append(create_table(table))

    story.append(Spacer(1,20))


# ==========================================================
# COST BREAKDOWN
# ==========================================================

def add_cost_breakdown(story, startup):

    story.append(section_title("Startup Cost Breakdown"))

    costs = startup.get("financial", {}).get("cost_breakdown", [])

    if not costs:

        story.append(
            paragraph("No cost breakdown available.")
        )

        story.append(Spacer(1,20))
        return

    table = [["Category", "Estimated Cost"]]

    for item in costs:

        table.append([

            item.get("category", "-"),

            item.get("amount", "-")

        ])

    story.append(create_table(table))

    story.append(Spacer(1,20))


# ==========================================================
# REVENUE STREAMS
# ==========================================================

def add_revenue_streams(story, startup):

    story.append(section_title("Revenue Streams"))

    revenue = startup.get("financial", {}).get("revenue_streams", [])

    if not revenue:

        story.append(
            paragraph("No revenue streams available.")
        )

    else:

        for stream in revenue:

            story.append(

                Paragraph(

                    f"• {stream}",

                    normal_style

                )

            )

    story.append(Spacer(1,20))


# ==========================================================
# FINANCIAL CHART
# ==========================================================

def add_financial_chart(story, startup):

    story.append(section_title("Financial Overview"))

    finance = startup.get("financial", {})

    investment = finance.get("investment_value", 50)

    revenue = finance.get("revenue_value", 80)

    profit = finance.get("profit_value", 60)

    drawing = Drawing(420,220)

    chart = VerticalBarChart()

    chart.x = 40

    chart.y = 40

    chart.height = 140

    chart.width = 300

    chart.data = [

        (

            investment,

            revenue,

            profit

        )

    ]

    chart.categoryAxis.categoryNames = [

        "Investment",

        "Revenue",

        "Profit"

    ]

    drawing.add(chart)

    story.append(drawing)

    story.append(Spacer(1,20))


# ==========================================================
# MARKETING STRATEGY
# ==========================================================

def add_marketing_strategy(story, startup):

    story.append(section_title("Marketing Strategy"))

    marketing = startup.get("marketing", {})

    items = [

        ("Target Audience",
         marketing.get("target_audience")),

        ("Marketing Channels",
         marketing.get("channels")),

        ("Customer Acquisition",
         marketing.get("acquisition")),

        ("Launch Strategy",
         marketing.get("launch_plan")),

        ("Growth Strategy",
         marketing.get("growth_strategy"))

    ]

    for title, value in items:

        story.append(

            Paragraph(

                f"<b>{title}</b>",

                subheading_style

            )

        )

        story.append(

            paragraph(value)

        )

        story.append(

            Spacer(1,8)

        )

    story.append(

        Spacer(1,20)

    )


# ==========================================================
# SOCIAL MEDIA PLAN
# ==========================================================

def add_social_media_plan(story, startup):

    story.append(section_title("Social Media Plan"))

    posts = startup.get(

        "marketing",

        {}

    ).get(

        "social_posts",

        []

    )

    if not posts:

        story.append(

            paragraph("No social media plan available.")

        )

    else:

        for post in posts:

            story.append(

                Paragraph(

                    f"• {post}",

                    normal_style

                )

            )

    story.append(

        Spacer(1,20)

    )


# ==========================================================
# MARKETING TIMELINE
# ==========================================================

def add_marketing_timeline(story, startup):

    story.append(

        section_title(

            "Launch Timeline"

        )

    )

    timeline = startup.get(

        "marketing",

        {}

    ).get(

        "timeline",

        []

    )

    if not timeline:

        story.append(

            paragraph(

                "No launch timeline available."

            )

        )

    else:

        table = [

            ["Phase", "Activity"]

        ]

        for step in timeline:

            table.append([

                step.get("phase", "-"),

                step.get("activity", "-")

            ])

        story.append(

            create_table(table)

        )

    story.append(

        Spacer(1,20)

    )
    # ==========================================================
# WEBSITE BLUEPRINT
# ==========================================================

def add_website_blueprint(story, startup):

    story.append(section_title("Website Blueprint"))

    website = startup.get("website", {})

    fields = [

        ("Website Type", website.get("type")),

        ("Recommended Pages", website.get("pages")),

        ("Core Features", website.get("features")),

        ("Technology Stack", website.get("tech_stack")),

        ("SEO Strategy", website.get("seo")),

        ("Call To Action", website.get("cta"))

    ]

    for title, value in fields:

        story.append(
            Paragraph(f"<b>{title}</b>", subheading_style)
        )

        story.append(
            paragraph(value)
        )

        story.append(
            Spacer(1,8)
        )

    story.append(Spacer(1,20))


# ==========================================================
# LEGAL REQUIREMENTS
# ==========================================================

def add_legal_requirements(story, startup):

    story.append(section_title("Legal & Compliance"))

    legal = startup.get("legal", {})

    table = [

        ["Requirement", "Details"],

        ["Business Registration",
         legal.get("registration","-")],

        ["Licenses",
         legal.get("licenses","-")],

        ["Tax Registration",
         legal.get("tax","-")],

        ["Compliance",
         legal.get("compliance","-")],

        ["Risks",
         legal.get("risks","-")]

    ]

    story.append(
        create_table(table)
    )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# PITCH DECK SUMMARY
# ==========================================================

def add_pitchdeck_summary(story, startup):

    story.append(section_title("Investor Pitch Summary"))

    pitch = startup.get("pitchdeck", {})

    sections = [

        ("Vision", pitch.get("vision")),

        ("Problem", pitch.get("problem")),

        ("Solution", pitch.get("solution")),

        ("Market Opportunity", pitch.get("market")),

        ("Business Model", pitch.get("business_model")),

        ("Funding Required", pitch.get("investment")),

        ("Use of Funds", pitch.get("fund_usage"))

    ]

    for title, value in sections:

        story.append(
            Paragraph(
                f"<b>{title}</b>",
                subheading_style
            )
        )

        story.append(
            paragraph(value)
        )

        story.append(
            Spacer(1,8)
        )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# STARTUP SCORECARD
# ==========================================================

def add_startup_scorecard(story, startup):

    story.append(
        section_title("Startup Scorecard")
    )

    score = startup.get("scorecard", {})

    table = [

        ["Category", "Score"],

        ["Innovation",
         score.get("innovation","-")],

        ["Market Potential",
         score.get("market","-")],

        ["Financial Feasibility",
         score.get("finance","-")],

        ["Scalability",
         score.get("scalability","-")],

        ["Execution",
         score.get("execution","-")],

        ["Overall Score",
         score.get("overall","-")]

    ]

    story.append(
        create_table(table)
    )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# AI RECOMMENDATIONS
# ==========================================================

def add_ai_recommendations(story, startup):

    story.append(
        section_title("AI Recommendations")
    )

    recommendations = startup.get(
        "recommendations",
        []
    )

    if not recommendations:

        story.append(
            paragraph("No recommendations generated.")
        )

    else:

        for item in recommendations:

            story.append(
                Paragraph(
                    f"• {item}",
                    normal_style
                )
            )

    story.append(
        Spacer(1,20)
    )


# ==========================================================
# CONCLUSION
# ==========================================================

def add_conclusion(story, startup):

    story.append(
        section_title("Conclusion")
    )

    conclusion = startup.get(

        "conclusion",

        "This startup demonstrates promising potential based on the AI-generated market, financial, branding, and operational analysis. Further validation through customer research and execution planning is recommended."

    )

    story.append(

        paragraph(conclusion)

    )

    story.append(

        Spacer(1,30)

    )


# ==========================================================
# END PAGE
# ==========================================================

def add_end_page(story):

    story.append(PageBreak())

    story.append(
        Spacer(1,2*inch)
    )

    story.append(
        Paragraph(
            "Thank You",
            title_style
        )
    )

    story.append(
        Spacer(1,0.4*inch)
    )

    story.append(
        Paragraph(
            "Generated using AgentX Startup Builder",
            center_style
        )
    )

    story.append(
        Spacer(1,0.2*inch)
    )

    story.append(
        Paragraph(
            "AI-powered multi-agent startup generation platform",
            center_style
        )
    )
    # ==========================================================
# SAFE VALUE HELPERS
# ==========================================================

def safe_text(value, default="-"):
    """
    Returns printable text.
    """

    if value is None:
        return default

    if isinstance(value, str):

        if value.strip() == "":
            return default

        return value

    return str(value)


def safe_list(value):

    if value is None:
        return []

    if isinstance(value, list):
        return value

    return [value]


def safe_dict(value):

    if value is None:
        return {}

    if isinstance(value, dict):
        return value

    return {}


# ==========================================================
# BULLET LIST
# ==========================================================

def bullet_list(story, items):

    items = safe_list(items)

    if not items:

        story.append(paragraph("No information available."))
        return

    for item in items:

        story.append(

            Paragraph(

                f"• {safe_text(item)}",

                normal_style

            )

        )


# ==========================================================
# KEY VALUE TABLE
# ==========================================================

def key_value_table(data):

    table = [["Field", "Value"]]

    for key, value in data.items():

        table.append([

            safe_text(key),

            safe_text(value)

        ])

    return create_table(table)


# ==========================================================
# HORIZONTAL DIVIDER
# ==========================================================

def divider(story):

    table = Table(

        [[""]],

        colWidths=[470]

    )

    table.setStyle(

        TableStyle([

            ("LINEBELOW",

             (0,0),

             (-1,-1),

             0.5,

             colors.grey)

        ])

    )

    story.append(table)

    story.append(Spacer(1,15))


# ==========================================================
# OPTIONAL LOGO
# ==========================================================

from reportlab.platypus import Image

def add_logo(story, logo_path):

    if not logo_path:

        return

    if not os.path.exists(logo_path):

        return

    try:

        image = Image(

            logo_path,

            width=1.3*inch,

            height=1.3*inch

        )

        story.append(image)

        story.append(Spacer(1,15))

    except Exception:

        pass


# ==========================================================
# PDF METADATA
# ==========================================================

def set_metadata(canvas, doc):

    canvas.setAuthor(

        "AgentX Startup Builder"

    )

    canvas.setTitle(

        "Startup Business Report"

    )

    canvas.setSubject(

        "AI Generated Startup Report"

    )

    canvas.setCreator(

        "AgentX Multi-Agent AI"

    )


# ==========================================================
# COVER PAGE WITH OPTIONAL LOGO
# ==========================================================

def add_cover_logo(story, startup):

    logo = startup.get("logo")

    add_logo(

        story,

        logo

    )


# ==========================================================
# GENERIC SECTION
# ==========================================================

def generic_section(

    story,

    heading,

    content

):

    story.append(

        section_title(

            heading

        )

    )

    story.append(

        paragraph(

            safe_text(

                content

            )

        )

    )

    story.append(

        Spacer(1,18)

    )


# ==========================================================
# ERROR PAGE
# ==========================================================

def error_page(story, message):

    story.append(

        section_title(

            "Report Generation Error"

        )

    )

    story.append(

        paragraph(message)

    )