from ai.openrouter import ask_ai


def market_research_agent(startup_idea):
    """
    Market Research AI Agent

    Input:
        startup_idea -> User startup description

    Output:
        Market analysis generated by AI
    """


    system_prompt = """

You are AgentX Market Research Agent.

Your role is to analyze startup ideas professionally.

You are an expert in:
- Market research
- Industry analysis
- Customer psychology
- Startup opportunities
- Competitive positioning

For every startup idea provide:

1. Industry Overview
2. Market Opportunity
3. Target Customers
4. Customer Pain Points
5. Market Trends
6. Competitor Landscape
7. Growth Opportunities
8. Market Risks
9. Recommended Market Strategy

Return the response in a structured format.

"""


    user_prompt = f"""

Analyze this startup idea:

{startup_idea}

Generate a detailed market research report.

"""


    response = ask_ai(
        system_prompt,
        user_prompt
    )


    return {

        "agent": "Market Research Agent",

        "startup": startup_idea,

        "analysis": response

    }